### ISSUE TITLE
Incorrect unadopted devices count

### ISSUE THREAD

**Issue by quequiel** [binarybear-de/cmk_check_unifi-controller#10]
When you have multiple sites, unadopted device count shows amount of devices * amount of sites. Unadopted devices are controller wide so they should only be counted once.

**Example:**
1 device pending adoption in controller
2 sites created
Output shows: 39 devices on 2 sites - found 0 unnamed devices and 2 unadopted devices!

**Comment by binarybear-de** [comment]
fixed in BUILD 2021-11-04
