### ISSUE TITLE
Cloud Key Gen2| parse error

### ISSUE THREAD

**Issue by tzockt** [binarybear-de/cmk_check_unifi-controller#13]
Hi, I wanted to install and use the script on our cloud key but I got this error

```
root@UniFi-CloudKey-Gen2:~# /usr/lib/check_mk_agent/local/check_unifi-controller.sh
parse error: Invalid numeric literal at line 1, column 4
parse error: Invalid numeric literal at line 1, column 4
parse error: Invalid numeric literal at line 1, column 4
0 UniFi-Controller - Hostname: , Build , Check-Script BUILD 2021-11-04-v3
parse error: Invalid numeric literal at line 1, column 4
0 UniFi-Devices devices=|sites=|unamed=0|unadopted=0  devices on  sites - no unnamed or unadopted devices found
````

**Comment by binarybear-de** [comment]
Currently the script only supports self-hosted UniFi installations, however support for appliances is planned (but it needs more time..)

UniFi CK and UDM seems to use a different API - see https://github.com/binarybear-de/cmk_check_unifi-controller/issues/9 for some details and possible ways to fix that until a new version is released..
