### ISSUE TITLE
Problem with Unifi 6.0.41.0

### ISSUE THREAD

**Issue by n00rm** [binarybear-de/cmk_check_unifi-controller#2]
Hey I'm running the latest Version of Unifi (6.0.41.0) on a Ubuntu 18.04 LTS. JQ is installed.
If I run the script I get the following error:

```
SUDOUSER@UNIFISERVER:/usr/lib/check_mk_agent/local$ sudo ./check_unifi-controller.sh 
./check_unifi-controller.sh: Zeile 134: [: =: Einstelliger (unärer) Operator erwartet.
./check_unifi-controller.sh: Zeile 137: [: =: Einstelliger (unärer) Operator erwartet.
3 UniFi-Controller - Build 
./check_unifi-controller.sh: Zeile 153: [: =: Einstelliger (unärer) Operator erwartet.
./check_unifi-controller.sh: Zeile 162: [: =: Einstelliger (unärer) Operator erwartet.
3 UniFi-Devices -
it@SRV-UNIFY:/usr/lib/check_mk_agent/local$ 
```

I think the different API Version from Unifi is the Problem because the API that is included in the current Version only supports Unifi Controller 5.X. versions

**Comment by n00rm** [comment]
Got it to work now after I changed the Base URL to localhost. Weird but it's working on the 6.0.X versions.

**Comment by binarybear-de** [comment]
Happens when controller couldn't be contacted correctly / wrong user in my case.
Added requirement of a successful login bind before continuing

Cheers.
